### ISSUE TITLE
Kickoff

### ISSUE THREAD

**Issue by aseguragonzalez** [habanero-squad/tropico#1]
**Requirements**
1. Must initialize the project, setting up the folder structure and workflows for CI.
2. Must define documentation workflow inside of CI tasks.

**Tasks**
- [ ] Create project structure
- [ ] Set gitignore
- [ ] Set run script
- [ ] Set docker-compose for local environment
   - [ ] Database
   - [ ] Mqtt Server
     - [ ] Set basic authentication
     - [ ] Document the credential creation process
   - [ ] Monitoring: (Metrics + Traces + Logs)
- [ ]  Complete readme and others project guidelines
