### ISSUE TITLE
Models and operations

### ISSUE THREAD

**Issue by aseguragonzalez** [habanero-squad/tropico#2]
**Requirements**
1. Must identify operations for measure storage, alerting and reporting.
2. Have to decide and define the contracts for measure messages from the devices (static and mobile devices).
3. Must complete the system architecture model.
4. Have to design the domain model for storage, alerting and reporting.

**Tasks**
- [ ] Implement Open API file.
- [ ] Setup redoc portal for the API definition.
- [ ] Investigate how to document MQTT contracts and publish it
- [ ] Complete the business workflow documents
- [ ] Complete the design document
